name: duck_hunter

on:
  push:
    paths:
      - 'duck_hunter.py'
      - '.github/workflows/duck_hunter.yml'
  schedule:
    - cron: '10 08 * * *' # 北京时间 16:10
  workflow_dispatch:

# 显式添加权限声明
permissions:
  contents: write

jobs:
  run_hunter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pandas
        run: pip install pandas

      - name: Run Duck Hunter Script
        run: python duck_hunter.py

      - name: Commit and Push Results
        run: |
          git config --local user.email "duck-hunter-bot@github.com"
          git config --local user.name "DuckHunterBot"
          git add results/
          # 检查是否有文件更改，避免没有结果时报错
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No new results found, skipping push."
          fi
